export const currentUser = {
  id: "1",
  name: "Alex Chen",
  email: "alex.chen@university.edu",
  avatar: "/professional-asian-student.jpg",
  headline: "Computer Science Student | AI Enthusiast | Building the Future",
  bio: "Passionate about leveraging AI to solve real-world problems. Currently exploring machine learning and its applications in healthcare.",
  location: "San Francisco, CA",
  university: "Stanford University",
  graduationYear: 2025,
  skills: ["Python", "Machine Learning", "React", "TensorFlow", "Data Analysis", "Cloud Computing"],
  interests: ["AI/ML", "Healthcare Tech", "Startups", "Open Source"],
  connections: 847,
  profileViews: 234,
  searchAppearances: 89,
  completedProjects: 12,
  extracurriculars: [
    {
      id: "1",
      title: "AI Research Assistant",
      organization: "Stanford AI Lab",
      type: "Research",
      startDate: "Sep 2023",
      endDate: "Present",
      description: "Working on natural language processing projects under Prof. Manning",
      logo: "/stanford-logo.png",
    },
    {
      id: "2",
      title: "President",
      organization: "Hackathon Club",
      type: "Leadership",
      startDate: "Jan 2023",
      endDate: "Present",
      description: "Leading a team of 50+ members to organize quarterly hackathons",
      logo: "/hackathon-logo.jpg",
    },
    {
      id: "3",
      title: "Open Source Contributor",
      organization: "TensorFlow",
      type: "Technical",
      startDate: "Jun 2022",
      endDate: "Present",
      description: "Contributing to documentation and bug fixes for TensorFlow library",
      logo: "/tensorflow-logo.png",
    },
  ],
  achievements: [
    { id: "1", title: "Dean's List", date: "Fall 2023", icon: "trophy" },
    { id: "2", title: "1st Place - HackMIT", date: "Oct 2023", icon: "award" },
    { id: "3", title: "Google CSSI Scholar", date: "Summer 2022", icon: "star" },
  ],
}

export const opportunities = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    title: "Machine Learning Engineering Intern",
    company: "Google",
    location: "Mountain View, CA",
    type: "Internship",
    matchScore: 95,
    deadline: "Jan 15, 2026",
    postedDate: "2 days ago",
    logo: "/google-logo.png",
    skills: ["Python", "TensorFlow", "Machine Learning"],
    description: "Join our ML team to work on cutting-edge AI projects",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    title: "Data Science Fellowship",
    company: "OpenAI",
    location: "San Francisco, CA",
    type: "Fellowship",
    matchScore: 92,
    deadline: "Feb 1, 2026",
    postedDate: "1 week ago",
    logo: "/abstract-geometric-logo.png",
    skills: ["Python", "Data Analysis", "AI/ML"],
    description: "12-week fellowship program focused on AI safety research",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    title: "Software Engineering Intern",
    company: "Stripe",
    location: "Remote",
    type: "Internship",
    matchScore: 88,
    deadline: "Jan 30, 2026",
    postedDate: "3 days ago",
    logo: "/stripe-logo.png",
    skills: ["React", "TypeScript", "Node.js"],
    description: "Build the future of payments infrastructure",
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    title: "AI Research Scholarship",
    company: "Microsoft Research",
    location: "Redmond, WA",
    type: "Scholarship",
    matchScore: 85,
    deadline: "Mar 1, 2026",
    postedDate: "5 days ago",
    logo: "/microsoft-logo.png",
    skills: ["Research", "Machine Learning", "Publication"],
    description: "$25,000 scholarship for AI research excellence",
  },
]

export const suggestedConnections = [
  {
    id: "1",
    name: "Sarah Kim",
    headline: "ML Engineer at Meta | Stanford CS '23",
    avatar: "/professional-woman-engineer.png",
    mutualConnections: 12,
    matchReason: "Similar interests in AI/ML and Stanford network",
  },
  {
    id: "2",
    name: "David Patel",
    headline: "Founder @ HealthAI | Y Combinator W24",
    avatar: "/professional-man-founder.png",
    mutualConnections: 8,
    matchReason: "Shared interest in healthcare technology",
  },
  {
    id: "3",
    name: "Emily Zhang",
    headline: "Product Manager at Notion | Berkeley '22",
    avatar: "/professional-woman-pm.jpg",
    mutualConnections: 5,
    matchReason: "Active in Bay Area tech community",
  },
]

export const projects = [
  {
    id: "1",
    title: "MediScan AI",
    description: "AI-powered medical image analysis tool for early disease detection",
    image: "/medical-ai-dashboard.jpg",
    status: "In Progress",
    collaborators: 3,
    likes: 45,
    views: 234,
    tags: ["Healthcare", "AI/ML", "Python"],
    progress: 75,
  },
  {
    id: "2",
    title: "EcoTrack",
    description: "Carbon footprint tracker using IoT sensors and machine learning",
    image: "/sustainability-app-dashboard.png",
    status: "Completed",
    collaborators: 4,
    likes: 89,
    views: 567,
    tags: ["Sustainability", "IoT", "React"],
    progress: 100,
  },
]

export const allProjects = [
  {
    id: "1",
    title: "MediScan AI",
    description:
      "AI-powered medical image analysis tool for early disease detection using convolutional neural networks and transfer learning techniques.",
    image: "/medical-ai-dashboard.jpg",
    category: "software",
    status: "In Progress",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Lead Developer" },
      { id: "2", name: "Sarah Kim", avatar: "/professional-woman-engineer.png", role: "ML Engineer" },
      { id: "3", name: "David Patel", avatar: "/professional-man-founder.png", role: "Product Advisor" },
    ],
    likes: 45,
    views: 234,
    comments: 12,
    tags: ["Healthcare", "AI/ML", "Python", "TensorFlow", "Computer Vision"],
    progress: 75,
    createdAt: "Oct 2025",
    updatedAt: "2 days ago",
    links: [
      { type: "github", label: "GitHub Repository", url: "https://github.com/alexchen/mediscan-ai" },
      { type: "demo", label: "Live Demo", url: "https://mediscan-ai.demo.com" },
    ],
    lookingFor: ["Backend Developer", "Data Scientist"],
  },
  {
    id: "2",
    title: "EcoTrack",
    description:
      "Carbon footprint tracker using IoT sensors and machine learning to help individuals and organizations reduce their environmental impact.",
    image: "/sustainability-app-dashboard.png",
    category: "environment",
    status: "Completed",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Full Stack Developer" },
      { id: "4", name: "Emily Zhang", avatar: "/professional-woman-pm.jpg", role: "Product Manager" },
      { id: "5", name: "James Wilson", avatar: "/professional-man-engineer.png", role: "IoT Specialist" },
      { id: "6", name: "Priya Sharma", avatar: "/professional-woman-data.png", role: "Data Analyst" },
    ],
    likes: 89,
    views: 567,
    comments: 28,
    tags: ["Sustainability", "IoT", "React", "Node.js", "MongoDB"],
    progress: 100,
    createdAt: "Jun 2025",
    updatedAt: "1 month ago",
    links: [
      { type: "github", label: "GitHub Repository", url: "https://github.com/alexchen/ecotrack" },
      { type: "demo", label: "Live App", url: "https://ecotrack.app" },
      { type: "impact", label: "Impact Report", url: "https://ecotrack.app/impact" },
    ],
    lookingFor: [],
  },
  {
    id: "3",
    title: "StudyBuddy AI",
    description:
      "An AI-powered study assistant that creates personalized learning paths, generates practice questions, and provides real-time tutoring.",
    image: "/study-ai-app.png",
    category: "education",
    status: "In Progress",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Lead Developer" },
      { id: "2", name: "Sarah Kim", avatar: "/professional-woman-engineer.png", role: "AI Engineer" },
    ],
    likes: 32,
    views: 178,
    comments: 8,
    tags: ["EdTech", "AI/ML", "React", "GPT", "Education"],
    progress: 45,
    createdAt: "Dec 2025",
    updatedAt: "1 day ago",
    links: [
      { type: "github", label: "GitHub Repository", url: "https://github.com/alexchen/studybuddy" },
    ],
    lookingFor: ["UI/UX Designer", "Educational Content Creator"],
  },
  {
    id: "4",
    title: "FinanceFlow",
    description:
      "Personal finance management app with AI-powered insights, budget tracking, and investment recommendations for young professionals.",
    image: "/finance-app.png",
    category: "business",
    status: "Planning",
    visibility: "private",
    collaborators: [{ id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Founder" }],
    likes: 12,
    views: 45,
    comments: 3,
    tags: ["FinTech", "React Native", "AI", "Personal Finance"],
    progress: 15,
    createdAt: "Jan 2026",
    updatedAt: "5 hours ago",
    links: [],
    lookingFor: ["Mobile Developer", "Finance Expert", "UI Designer"],
  },
  {
    id: "5",
    title: "Campus Art Collective",
    description:
      "A student-led art collective showcasing diverse creative works from painters, sculptors, digital artists, and photographers across campus.",
    image: "/art-collective.jpg",
    category: "creative",
    status: "In Progress",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Curator" },
    ],
    likes: 67,
    views: 320,
    comments: 15,
    tags: ["Art", "Community", "Exhibition", "Photography", "Digital Art"],
    progress: 60,
    createdAt: "Sep 2025",
    updatedAt: "3 days ago",
    links: [
      { type: "portfolio", label: "Gallery", url: "https://campusartcollective.com" },
      { type: "instagram", label: "Instagram", url: "https://instagram.com/campusartcollective" },
    ],
    lookingFor: ["Graphic Designer", "Event Coordinator"],
  },
  {
    id: "6",
    title: "Undergraduate Research: Climate Modeling",
    description:
      "Research project analyzing regional climate patterns using machine learning to predict extreme weather events with improved accuracy.",
    image: "/research-climate.jpg",
    category: "research",
    status: "In Progress",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Research Lead" },
    ],
    likes: 28,
    views: 156,
    comments: 7,
    tags: ["Climate Science", "Research", "Machine Learning", "Data Analysis"],
    progress: 40,
    createdAt: "Nov 2025",
    updatedAt: "1 week ago",
    links: [
      { type: "paper", label: "Draft Paper", url: "https://arxiv.org/example" },
      { type: "data", label: "Dataset", url: "https://kaggle.com/example" },
    ],
    lookingFor: ["Data Scientist", "Climate Science Student"],
  },
  {
    id: "7",
    title: "TEDx University Event",
    description:
      "Organizing the annual TEDx event featuring student speakers, industry leaders, and interactive workshops on innovation and social change.",
    image: "/tedx-event.jpg",
    category: "event",
    status: "Planning",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Event Director" },
    ],
    likes: 94,
    views: 445,
    comments: 22,
    tags: ["TEDx", "Public Speaking", "Event Planning", "Leadership"],
    progress: 25,
    createdAt: "Dec 2025",
    updatedAt: "2 days ago",
    links: [
      { type: "website", label: "Event Website", url: "https://tedxuniversity.com" },
      { type: "registration", label: "Register", url: "https://tedxuniversity.com/register" },
    ],
    lookingFor: ["Marketing Lead", "Speaker Coordinator", "Volunteers"],
  },
  {
    id: "8",
    title: "Community Garden Initiative",
    description:
      "Building sustainable community gardens across underserved neighborhoods to promote food security, environmental education, and community bonding.",
    image: "/community-garden.jpg",
    category: "community",
    status: "In Progress",
    visibility: "public",
    collaborators: [
      { id: "1", name: "Alex Chen", avatar: "/professional-asian-student.jpg", role: "Project Lead" },
    ],
    likes: 112,
    views: 678,
    comments: 35,
    tags: ["Community Service", "Sustainability", "Food Security", "Volunteering"],
    progress: 55,
    createdAt: "Aug 2025",
    updatedAt: "4 days ago",
    links: [
      { type: "website", label: "Website", url: "https://communitygarden.org" },
      { type: "donation", label: "Donate", url: "https://communitygarden.org/donate" },
      { type: "social", label: "Facebook", url: "https://facebook.com/communitygarden" },
    ],
    lookingFor: ["Volunteer Coordinator", "Grant Writer"],
  },
]

export const projectUpdates = [
  {
    id: "1",
    projectId: "1",
    projectTitle: "MediScan AI",
    type: "milestone",
    content: "Achieved 95% accuracy on chest X-ray classification",
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    projectId: "3",
    projectTitle: "StudyBuddy AI",
    type: "update",
    content: "Integrated GPT-4 for personalized question generation",
    timestamp: "1 day ago",
  },
  {
    id: "3",
    projectId: "2",
    projectTitle: "EcoTrack",
    type: "feature",
    content: "Added community challenges feature with leaderboards",
    timestamp: "1 week ago",
  },
]

export const events = [
  {
    id: "1",
    title: "AI Summit 2026",
    date: "Feb 15-17, 2026",
    location: "San Francisco, CA",
    type: "Conference",
    attendees: 5000,
    image: "/tech-conference.png",
  },
  {
    id: "2",
    title: "TreeHacks 2026",
    date: "Feb 21-23, 2026",
    location: "Stanford University",
    type: "Hackathon",
    attendees: 1500,
    image: "/hackathon-event.png",
  },
]

export const applications = [
  {
    id: "1",
    company: "Google",
    position: "ML Engineering Intern",
    status: "Interview Scheduled",
    appliedDate: "Dec 15, 2025",
    nextStep: "Technical Interview - Jan 10",
  },
  {
    id: "2",
    company: "Meta",
    position: "Software Engineering Intern",
    status: "Under Review",
    appliedDate: "Dec 10, 2025",
    nextStep: "Awaiting response",
  },
  {
    id: "3",
    company: "Apple",
    position: "iOS Development Intern",
    status: "Applied",
    appliedDate: "Jan 2, 2026",
    nextStep: "Application submitted",
  },
]

export const analyticsData = {
  profileViews: [
    { date: "Mon", views: 23 },
    { date: "Tue", views: 45 },
    { date: "Wed", views: 32 },
    { date: "Thu", views: 67 },
    { date: "Fri", views: 54 },
    { date: "Sat", views: 28 },
    { date: "Sun", views: 41 },
  ],
  networkGrowth: [
    { month: "Aug", connections: 450 },
    { month: "Sep", connections: 520 },
    { month: "Oct", connections: 610 },
    { month: "Nov", connections: 720 },
    { month: "Dec", connections: 847 },
  ],
  skillEndorsements: [
    { skill: "Python", count: 45 },
    { skill: "Machine Learning", count: 38 },
    { skill: "React", count: 32 },
    { skill: "TensorFlow", count: 28 },
    { skill: "Data Analysis", count: 24 },
  ],
}

export const allOpportunities = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    title: "Machine Learning Engineering Intern",
    company: "Google",
    location: "Mountain View, CA",
    type: "Internship",
    matchScore: 95,
    deadline: "Jan 15, 2026",
    postedDate: "2 days ago",
    logo: "/google-logo.png",
    skills: ["Python", "TensorFlow", "Machine Learning", "Data Structures"],
    description: "Join our ML team to work on cutting-edge AI projects that impact billions of users worldwide.",
    salary: "$8,500/month",
    duration: "12 weeks",
    remote: false,
    applicants: 234,
    saved: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    title: "Data Science Fellowship",
    company: "OpenAI",
    location: "San Francisco, CA",
    type: "Fellowship",
    matchScore: 92,
    deadline: "Feb 1, 2026",
    postedDate: "1 week ago",
    logo: "/abstract-geometric-logo.png",
    skills: ["Python", "Data Analysis", "AI/ML", "Research"],
    description: "12-week fellowship program focused on AI safety research and alignment.",
    salary: "$10,000/month",
    duration: "12 weeks",
    remote: true,
    applicants: 567,
    saved: true,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    title: "Software Engineering Intern",
    company: "Stripe",
    location: "Remote",
    type: "Internship",
    matchScore: 88,
    deadline: "Jan 30, 2026",
    postedDate: "3 days ago",
    logo: "/stripe-logo.png",
    skills: ["React", "TypeScript", "Node.js", "APIs"],
    description: "Build the future of payments infrastructure and work with world-class engineers.",
    salary: "$9,000/month",
    duration: "10 weeks",
    remote: true,
    applicants: 189,
    saved: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    title: "AI Research Scholarship",
    company: "Microsoft Research",
    location: "Redmond, WA",
    type: "Scholarship",
    matchScore: 85,
    deadline: "Mar 1, 2026",
    postedDate: "5 days ago",
    logo: "/microsoft-logo.png",
    skills: ["Research", "Machine Learning", "Publication", "Academic Writing"],
    description: "$25,000 scholarship for AI research excellence and innovation.",
    salary: "$25,000 grant",
    duration: "1 year",
    remote: false,
    applicants: 423,
    saved: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    title: "Product Design Intern",
    company: "Figma",
    location: "San Francisco, CA",
    type: "Internship",
    matchScore: 72,
    deadline: "Feb 15, 2026",
    postedDate: "1 day ago",
    logo: "/figma-logo.png",
    skills: ["UI/UX", "Figma", "Prototyping", "User Research"],
    description: "Design the future of creative tools used by millions of designers.",
    salary: "$7,500/month",
    duration: "12 weeks",
    remote: false,
    applicants: 156,
    saved: false,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    title: "Blockchain Development Competition",
    company: "Ethereum Foundation",
    location: "Virtual",
    type: "Competition",
    matchScore: 68,
    deadline: "Jan 20, 2026",
    postedDate: "4 days ago",
    logo: "/ethereum-logo.png",
    skills: ["Solidity", "Web3", "Smart Contracts", "DeFi"],
    description: "Build innovative dApps and compete for $100,000 in prizes.",
    salary: "Up to $50,000",
    duration: "8 weeks",
    remote: true,
    applicants: 890,
    saved: true,
  },
]

export const networkConnections = [
  {
    id: "1",
    name: "Sarah Kim",
    headline: "ML Engineer at Meta | Stanford CS '23",
    avatar: "/professional-woman-engineer.png",
    mutualConnections: 12,
    matchReason: "Similar interests in AI/ML and Stanford network",
    status: "connected" as const,
    connectedDate: "Nov 2025",
  },
  {
    id: "2",
    name: "David Patel",
    headline: "Founder @ HealthAI | Y Combinator W24",
    avatar: "/professional-man-founder.png",
    mutualConnections: 8,
    matchReason: "Shared interest in healthcare technology",
    status: "connected" as const,
    connectedDate: "Oct 2025",
  },
  {
    id: "3",
    name: "Emily Zhang",
    headline: "Product Manager at Notion | Berkeley '22",
    avatar: "/professional-woman-pm.jpg",
    mutualConnections: 5,
    matchReason: "Active in Bay Area tech community",
    status: "pending" as const,
    connectedDate: null,
  },
  {
    id: "4",
    name: "James Wilson",
    headline: "Senior Software Engineer at Apple",
    avatar: "/professional-man-engineer.png",
    mutualConnections: 15,
    matchReason: "Works on ML infrastructure you're interested in",
    status: "connected" as const,
    connectedDate: "Dec 2025",
  },
  {
    id: "5",
    name: "Priya Sharma",
    headline: "Data Scientist at Netflix | MIT '22",
    avatar: "/professional-woman-data.png",
    mutualConnections: 7,
    matchReason: "Similar research interests in recommendation systems",
    status: "suggested" as const,
    connectedDate: null,
  },
  {
    id: "6",
    name: "Michael Chang",
    headline: "VP Engineering at Stripe",
    avatar: "/professional-man-vp.png",
    mutualConnections: 3,
    matchReason: "Hiring for roles matching your skills",
    status: "suggested" as const,
    connectedDate: null,
  },
]

export const messages = [
  {
    id: "1",
    senderId: "1",
    senderName: "Sarah Kim",
    senderAvatar: "/professional-woman-engineer.png",
    preview: "Hey! I saw your project on medical AI. Would love to chat about...",
    timestamp: "2 hours ago",
    unread: true,
  },
  {
    id: "2",
    senderId: "2",
    senderName: "David Patel",
    senderAvatar: "/professional-man-founder.png",
    preview: "Thanks for connecting! Let me know if you'd like to discuss...",
    timestamp: "1 day ago",
    unread: false,
  },
  {
    id: "3",
    senderId: "4",
    senderName: "James Wilson",
    senderAvatar: "/professional-man-engineer.png",
    preview: "Great meeting you at the hackathon! Here are some resources...",
    timestamp: "3 days ago",
    unread: false,
  },
]
